version: "3"
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=yavuzlarrestaurant
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
